dist: bionic
language: java
jdk: openjdk8

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu

  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install gradle

install: gradle wrapper

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: gradle cucumber